# Generated by Django 4.1.2 on 2022-10-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shortener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(unique=True)),
                ("short_url", models.CharField(blank=True, max_length=6, unique=True)),
                (
                    "redirect_link",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                ("last_redirect_time", models.DateTimeField(null=True)),
                ("redirect_count", models.IntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                ("ip", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
