# Generated by Django 4.1.2 on 2022-10-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0005_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["-count"]},
        ),
    ]
