# Generated by Django 4.1.2 on 2022-10-24 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0006_alter_country_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countries",
                to="shortener.shortener",
            ),
        ),
    ]
