# Generated by Django 4.1.2 on 2022-10-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0007_alter_country_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shortener",
            options={"ordering": ["-id"]},
        ),
    ]
